version: 0.2

env:
  variables:
    DB_HOST: "localhost"
    DB_USERNAME: "drill_sergeant"
    DB_TEST_NAME: "civiclens_test"
    DB_PROD_NAME: "civiclens_production"

    VITE_SERVER_URL: "http://localhost:4000/api"
    VITE_REGISTER_USER_PATH: "/auth/register"
    VITE_LOGIN_USER_PATH: "/auth/login"
    VITE_VERIFY_TOKEN_PATH: "/auth/me"
    VITE_CREATE_ISSUE_PATH: "/issues/"
    VITE_GET_ALL_ISSUES_PATH: "/issues/"
    VITE_UPVOTE_ISSUE_PATH: "/issues/"
  secrets-manager:
    DB_PASSWORD: "arn:aws:secretsmanager:us-east-2:637739133331:secret:civiclens/db-passsword-OocwkV"
    VITE_ADOBE_URL: "arn:aws:secretsmanager:us-east-2:637739133331:secret:civiclens/adobe-url-nr1MkV"
    VITE_FONT_AWESOME_URL: "arn:aws:secretsmanager:us-east-2:637739133331:secret:civiclens/font-awesome-url-CWuphK"
phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR/server
      - npm install
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/server
      - echo "Checking DB_PASSWORD length..."
      - echo ${DB_PASSWORD} | wc -c
      # 1. Use the ECR public mirror to avoid Docker Hub rate limits
      - docker run --name postgres-test -e POSTGRES_USER=drill_sergeant -e POSTGRES_PASSWORD=$DB_PASSWORD -e POSTGRES_DB=postgres -p 5432:5432 -d public.ecr.aws/docker/library/postgres:15-alpine
      - sleep 10
      - echo "Creating database 'civiclens_test'..."
      - docker exec -e PGPASSWORD=$DB_PASSWORD postgres-test psql -U drill_sergeant -d postgres -c "CREATE DATABASE civiclens_test;"
      # 2. Run the sync script we created
      - chmod +x scripts/db-sync.sh
      - NODE_ENV=test ./scripts/db-sync.sh
      - echo "Running tests..."
      - export DB_NAME=$DB_TEST_NAME
      - NODE_ENV=test npm test
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/server
      - echo Building for production...
      - export DB_NAME=$DB_PROD_NAME
      - npm run build
  post_build:
    commands:
      - docker stop postgres-test
      - docker rm postgres-test
